package com.miguelcaldas.mcsmsforwardermultichannel.util

import android.annotation.SuppressLint
import android.content.Context
import org.json.JSONArray
import org.json.JSONException
import org.json.JSONObject
import java.nio.CharBuffer
import java.nio.charset.CharacterCodingException
import java.security.GeneralSecurityException
import java.security.ProviderException
import java.util.Base64
import javax.crypto.AEADBadTagException
import javax.crypto.Cipher
import javax.crypto.Mac
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

internal data class ProvisionedWhatsApp(
    val enabled: Boolean,
    val phoneNumberId: String,
    val accessToken: String,
    val recipient: String,
)

internal data class ProvisionedTelegram(
    val enabled: Boolean,
    val botToken: String,
    val chatId: String,
)

internal data class ProvisionedSms(
    val enabled: Boolean,
    val destination: String,
)

internal data class ProvisionedFilters(
    val allowedSenders: List<SenderRule>?,
    val regexes: List<String>?,
    val forwardTemplate: String?,
)

internal data class ProvisionedConfiguration(
    val masterEnabled: Boolean?,
    val whatsApp: ProvisionedWhatsApp?,
    val telegram: ProvisionedTelegram?,
    val sms: ProvisionedSms?,
    val filters: ProvisionedFilters?,
)

internal data class MergedProvisioningEntries<T>(val values: List<T>, val addedCount: Int)

internal fun <T> mergeProvisioningEntries(
    existing: List<T>,
    additions: List<T>,
    equivalent: (T, T) -> Boolean,
): MergedProvisioningEntries<T> {
    val merged = existing.toMutableList()
    var addedCount = 0
    additions.forEach { candidate ->
        if (merged.none { equivalent(it, candidate) }) {
            merged.add(candidate)
            addedCount++
        }
    }
    return MergedProvisioningEntries(values = merged, addedCount = addedCount)
}

internal class ProvisioningException(message: String, cause: Throwable? = null): Exception(message, cause)

/** Decrypts and applies configuration bundles generated by tools/New-ProvisioningBundle.ps1. */
internal object ProvisioningBundle {
    const val MAX_BUNDLE_BYTES = 128 * 1024
    const val MAX_IMPORT_CODE_CHARS = 192 * 1024
    const val MINIMUM_PASSPHRASE_LENGTH = 12
    const val MAXIMUM_PASSPHRASE_LENGTH = 1024

    private const val FORMAT = "mc-sms-forwarder-config"
    private const val VERSION = 1
    private const val KDF_ALGORITHM = "PBKDF2-HMAC-SHA256"
    private const val CIPHER_ALGORITHM = "AES-256-GCM"
    private const val MINIMUM_KDF_ITERATIONS = 100_000
    private const val MAXIMUM_KDF_ITERATIONS = 2_000_000
    private const val KEY_BITS = 256
    private const val SALT_BYTES = 16
    private const val NONCE_BYTES = 12
    private const val TAG_BYTES = 16
    private const val GCM_TAG_BITS = TAG_BYTES * 8
    private const val MAXIMUM_LIST_ENTRIES = 1_000
    private const val MAXIMUM_TEMPLATE_LENGTH = 8_192
    private const val IMPORT_CODE_PREFIX = "mcsmsconfig:v1:"
    private val associatedData = "$FORMAT:v$VERSION".toByteArray(Charsets.UTF_8)

    fun decodeImportCode(importCode: String): String {
        val trimmed = importCode.trim()
        if (trimmed.length > MAX_IMPORT_CODE_CHARS) {
            throw ProvisioningException("The encrypted import code is too large.")
        }
        if (trimmed.startsWith("{")) {
            return trimmed
        }
        if (!trimmed.startsWith(IMPORT_CODE_PREFIX)) {
            throw ProvisioningException("This is not a valid MC SMS Forwarder import code.")
        }
        val encoded = trimmed.removePrefix(IMPORT_CODE_PREFIX)
        val decoded = try {
            Base64.getUrlDecoder().decode(encoded)
        } catch (error: IllegalArgumentException) {
            throw ProvisioningException("The encrypted import code is malformed.", error)
        }
        if (decoded.size > MAX_BUNDLE_BYTES) {
            decoded.fill(0)
            throw ProvisioningException("The configuration file is too large.")
        }
        return try {
            String(decoded, Charsets.UTF_8)
        } finally {
            decoded.fill(0)
        }
    }

    fun decrypt(bundleJson: String, passphrase: CharArray): ProvisionedConfiguration {
        if (
            bundleJson.length > MAX_BUNDLE_BYTES ||
            bundleJson.toByteArray(Charsets.UTF_8).size > MAX_BUNDLE_BYTES
        ) {
            throw ProvisioningException("The configuration file is too large.")
        }
        if (passphrase.size !in MINIMUM_PASSPHRASE_LENGTH..MAXIMUM_PASSPHRASE_LENGTH) {
            throw ProvisioningException(
                "Passphrase must contain $MINIMUM_PASSPHRASE_LENGTH to " +
                    "$MAXIMUM_PASSPHRASE_LENGTH characters.",
            )
        }

        val envelope = parseJson(bundleJson, "This is not a valid MC SMS Forwarder configuration file.")
        requireOnlyKeys(envelope, "envelope", setOf("format", "version", "kdf", "cipher"))
        if (requiredString(envelope, "format", 64) != FORMAT) {
            throw ProvisioningException("This configuration file is for a different application.")
        }
        if (requiredInteger(envelope, "version") != VERSION) {
            throw ProvisioningException("This configuration file version is not supported.")
        }

        val kdf = requiredObject(envelope, "kdf")
        requireOnlyKeys(kdf, "kdf", setOf("algorithm", "iterations", "salt"))
        if (requiredString(kdf, "algorithm", 64) != KDF_ALGORITHM) {
            throw ProvisioningException("This configuration uses an unsupported key derivation algorithm.")
        }
        val iterations = requiredInteger(kdf, "iterations")
        if (iterations !in MINIMUM_KDF_ITERATIONS..MAXIMUM_KDF_ITERATIONS) {
            throw ProvisioningException("The configuration key derivation cost is outside the supported range.")
        }
        val salt = requiredBase64(kdf, "salt", SALT_BYTES)

        val cipherEnvelope = requiredObject(envelope, "cipher")
        requireOnlyKeys(cipherEnvelope, "cipher", setOf("algorithm", "nonce", "ciphertext", "tag"))
        if (requiredString(cipherEnvelope, "algorithm", 64) != CIPHER_ALGORITHM) {
            throw ProvisioningException("This configuration uses an unsupported encryption algorithm.")
        }
        val nonce = requiredBase64(cipherEnvelope, "nonce", NONCE_BYTES)
        val ciphertext = requiredBase64(cipherEnvelope, "ciphertext")
        val tag = requiredBase64(cipherEnvelope, "tag", TAG_BYTES)
        if (ciphertext.isEmpty()) {
            throw ProvisioningException("The encrypted configuration payload is empty.")
        }

        val key = deriveKey(passphrase, salt, iterations)
        val authenticatedCiphertext = ciphertext + tag
        val plaintext = try {
            val cipher = Cipher.getInstance("AES/GCM/NoPadding")
            cipher.init(Cipher.DECRYPT_MODE, SecretKeySpec(key, "AES"), GCMParameterSpec(GCM_TAG_BITS, nonce))
            cipher.updateAAD(associatedData)
            cipher.doFinal(authenticatedCiphertext)
        } catch (error: AEADBadTagException) {
            throw ProvisioningException(
                "Could not decrypt the configuration. The passphrase is incorrect or the file was changed.",
                error,
            )
        } catch (error: GeneralSecurityException) {
            throw ProvisioningException("Android could not decrypt the configuration.", error)
        } finally {
            key.fill(0)
        }

        return try {
            parsePayload(String(plaintext, Charsets.UTF_8))
        } finally {
            plaintext.fill(0)
        }
    }

    @SuppressLint("UseKtx")
    fun save(context: Context, configuration: ProvisionedConfiguration): String {
        val prefs = context.getSharedPreferences(WhatsAppConfig.PREFS_NAME, Context.MODE_PRIVATE)
        val secretUpdates = buildMap {
            configuration.whatsApp?.let {
                put(SecureStore.KEY_WA_ACCESS_TOKEN, it.accessToken)
            }
            configuration.telegram?.let {
                put(SecureStore.KEY_TG_BOT_TOKEN, it.botToken)
            }
        }
        val previousSecrets = secretUpdates.keys.associateWith { SecureStore.read(context, it) }
        val previousMasterEnabled = MasterSwitchStore.load(prefs)
        val countryIso = SenderMatcher.deviceCountryIso(context)
        val mergedSenders = configuration.filters?.allowedSenders?.let { additions ->
            mergeProvisioningEntries(SenderListStore.load(prefs), additions) { existing, candidate ->
                SenderMatcher.equivalent(existing, candidate, countryIso)
            }
        }
        val mergedRegexes = configuration.filters?.regexes?.let { additions ->
            mergeProvisioningEntries(RegexListStore.load(prefs), additions) { existing, candidate ->
                existing == candidate
            }
        }
        val enabledKeys = buildSet {
            if (configuration.whatsApp != null) {
                add(WhatsAppConfig.KEY_ENABLED)
            }
            if (configuration.telegram != null) {
                add(TelegramConfig.KEY_ENABLED)
            }
            if (configuration.sms != null) {
                add(SmsConfig.KEY_ENABLED)
            }
        }
        val previousPreferences = PreferenceSnapshot.capture(
            prefs = prefs,
            keys = buildSet {
                add(MasterSwitchStore.KEY_ENABLED)
                if (configuration.whatsApp != null) {
                    add(WhatsAppConfig.KEY_ENABLED)
                    add(WhatsAppConfig.KEY_PHONE_NUMBER_ID)
                    add(WhatsAppConfig.KEY_RECIPIENT)
                }
                if (configuration.telegram != null) {
                    add(TelegramConfig.KEY_ENABLED)
                    add(TelegramConfig.KEY_CHAT_ID)
                }
                if (configuration.sms != null) {
                    add(SmsConfig.KEY_ENABLED)
                    add(SmsConfig.KEY_DESTINATION)
                }
                if (mergedSenders != null) {
                    add(SenderListStore.KEY)
                    add(SenderListStore.KEY_REGEX_FLAGS)
                }
                if (mergedRegexes != null) {
                    add(RegexListStore.KEY)
                }
                if (configuration.filters?.forwardTemplate != null) {
                    add(ForwardTemplate.KEY)
                }
            },
        )

        // Disable forwarding before staging every supplied field. If the process is interrupted,
        // it cannot send using a partially imported set of settings.
        val stagedEditor = prefs.edit().putBoolean(MasterSwitchStore.KEY_ENABLED, false)
        configuration.whatsApp?.let {
            stagedEditor
                .putBoolean(WhatsAppConfig.KEY_ENABLED, false)
                .putString(WhatsAppConfig.KEY_PHONE_NUMBER_ID, it.phoneNumberId)
                .putString(WhatsAppConfig.KEY_RECIPIENT, it.recipient)
        }
        configuration.telegram?.let {
            stagedEditor
                .putBoolean(TelegramConfig.KEY_ENABLED, false)
                .putString(TelegramConfig.KEY_CHAT_ID, it.chatId)
        }
        configuration.sms?.let {
            stagedEditor
                .putBoolean(SmsConfig.KEY_ENABLED, false)
                .putString(SmsConfig.KEY_DESTINATION, it.destination)
        }
        mergedSenders?.let {
            SenderListStore.write(stagedEditor, it.values)
        }
        mergedRegexes?.let {
            stagedEditor.putString(RegexListStore.KEY, it.values.joinToString("\n"))
        }
        configuration.filters?.forwardTemplate?.let {
            stagedEditor.putString(ForwardTemplate.KEY, it)
        }
        if (!stagedEditor.commit()) {
            val failure = ProvisioningException("Android could not save the imported configuration.")
            try {
                previousPreferences.restore(prefs)
            } catch (rollbackError: IllegalStateException) {
                failure.addSuppressed(rollbackError)
                disableForwarding(prefs, enabledKeys, failure)
            }
            throw failure
        }

        try {
            if (secretUpdates.isNotEmpty()) {
                SecureStore.writeAll(context, secretUpdates)
            }
            val enabledEditor = prefs.edit()
            configuration.whatsApp?.let {
                enabledEditor.putBoolean(WhatsAppConfig.KEY_ENABLED, it.enabled)
            }
            configuration.telegram?.let {
                enabledEditor.putBoolean(TelegramConfig.KEY_ENABLED, it.enabled)
            }
            configuration.sms?.let {
                enabledEditor.putBoolean(SmsConfig.KEY_ENABLED, it.enabled)
            }
            enabledEditor.putBoolean(
                MasterSwitchStore.KEY_ENABLED,
                configuration.masterEnabled ?: previousMasterEnabled,
            )
            if (!enabledEditor.commit()) {
                throw IllegalStateException("Could not enable imported channel configuration")
            }
        } catch (error: GeneralSecurityException) {
            rollbackAfterSaveFailure(context, prefs, previousSecrets, previousPreferences, enabledKeys, error)
        } catch (error: ProviderException) {
            rollbackAfterSaveFailure(context, prefs, previousSecrets, previousPreferences, enabledKeys, error)
        } catch (error: IllegalStateException) {
            rollbackAfterSaveFailure(context, prefs, previousSecrets, previousPreferences, enabledKeys, error)
        }

        val sendersAdded = mergedSenders?.addedCount ?: 0
        val regexesAdded = mergedRegexes?.addedCount ?: 0
        return "Imported configuration. Added $sendersAdded sender(s) and $regexesAdded rule(s); " +
            "supplied settings were updated."
    }

    private fun deriveKey(passphrase: CharArray, salt: ByteArray, iterations: Int): ByteArray {
        val passwordBytes = utf8Bytes(passphrase)
        val input = salt + byteArrayOf(0, 0, 0, 1)
        var previous = ByteArray(32)
        var current = ByteArray(32)
        val derivedKey = ByteArray(KEY_BITS / Byte.SIZE_BITS)
        return try {
            val mac = Mac.getInstance("HmacSHA256")
            mac.init(SecretKeySpec(passwordBytes, "HmacSHA256"))
            mac.update(input)
            mac.doFinal(previous, 0)
            previous.copyInto(derivedKey)
            repeat(iterations - 1) {
                mac.update(previous)
                mac.doFinal(current, 0)
                for (index in derivedKey.indices) {
                    derivedKey[index] = (derivedKey[index].toInt() xor current[index].toInt()).toByte()
                }
                val swap = previous
                previous = current
                current = swap
            }
            derivedKey
        } catch (error: GeneralSecurityException) {
            derivedKey.fill(0)
            throw ProvisioningException("Android could not derive the configuration encryption key.", error)
        } finally {
            passwordBytes.fill(0)
            input.fill(0)
            previous.fill(0)
            current.fill(0)
        }
    }

    private fun utf8Bytes(characters: CharArray): ByteArray {
        val encoded = try {
            Charsets.UTF_8.newEncoder().encode(CharBuffer.wrap(characters))
        } catch (error: CharacterCodingException) {
            throw ProvisioningException("The passphrase contains an invalid Unicode sequence.", error)
        }
        val bytes = ByteArray(encoded.remaining())
        encoded.get(bytes)
        if (encoded.hasArray()) {
            encoded.array().fill(0)
        }
        return bytes
    }

    private fun rollbackAfterSaveFailure(
        context: Context,
        prefs: android.content.SharedPreferences,
        previousSecrets: Map<String, String>,
        previousPreferences: PreferenceSnapshot,
        enabledKeys: Set<String>,
        cause: Throwable,
    ): Nothing {
        val failure = ProvisioningException("Android could not save the imported configuration.", cause)
        var secretsRestored = previousSecrets.isEmpty()
        if (previousSecrets.isNotEmpty()) {
            try {
                SecureStore.writeAll(context, previousSecrets)
                secretsRestored = true
            } catch (rollbackError: GeneralSecurityException) {
                failure.addSuppressed(rollbackError)
            } catch (rollbackError: ProviderException) {
                failure.addSuppressed(rollbackError)
            } catch (rollbackError: IllegalStateException) {
                failure.addSuppressed(rollbackError)
            }
        }

        if (secretsRestored) {
            try {
                previousPreferences.restore(prefs)
            } catch (rollbackError: IllegalStateException) {
                failure.addSuppressed(rollbackError)
                disableForwarding(prefs, enabledKeys, failure)
            }
        } else {
            disableForwarding(prefs, enabledKeys, failure)
        }
        throw failure
    }

    private fun disableForwarding(
        prefs: android.content.SharedPreferences,
        enabledKeys: Set<String>,
        failure: ProvisioningException,
    ) {
        val editor = prefs.edit().putBoolean(MasterSwitchStore.KEY_ENABLED, false)
        enabledKeys.forEach { editor.putBoolean(it, false) }
        if (!editor.commit()) {
            failure.addSuppressed(IllegalStateException("Could not disable partially imported forwarding"))
        }
    }

    private fun parsePayload(json: String): ProvisionedConfiguration {
        val payload = parseJson(json, "The decrypted configuration payload is invalid.")
        requireOnlyKeys(
            payload,
            "payload",
            setOf("masterEnabled", "whatsApp", "telegram", "sms", "filters"),
        )
        val masterEnabled = optionalBoolean(payload, "masterEnabled")
        val whatsApp = optionalObject(payload, "whatsApp")?.let {
            requireOnlyKeys(it, "whatsApp", setOf("enabled", "phoneNumberId", "accessToken", "recipient"))
            ProvisionedWhatsApp(
                enabled = requiredBoolean(it, "enabled"),
                phoneNumberId = requiredString(it, "phoneNumberId", 256),
                accessToken = requiredString(it, "accessToken", 8192),
                recipient = requiredString(it, "recipient", 64),
            )
        }
        val telegram = optionalObject(payload, "telegram")?.let {
            requireOnlyKeys(it, "telegram", setOf("enabled", "botToken", "chatId"))
            ProvisionedTelegram(
                enabled = requiredBoolean(it, "enabled"),
                botToken = requiredString(it, "botToken", 1024),
                chatId = requiredString(it, "chatId", 128),
            )
        }
        val sms = optionalObject(payload, "sms")?.let {
            requireOnlyKeys(it, "sms", setOf("enabled", "destination"))
            ProvisionedSms(
                enabled = requiredBoolean(it, "enabled"),
                destination = requiredString(it, "destination", 64),
            )
        }
        val filters = optionalObject(payload, "filters")?.let {
            requireOnlyKeys(it, "filters", setOf("allowedSenders", "regexes", "forwardTemplate"))
            ProvisionedFilters(
                allowedSenders = optionalSenderRuleList(it, "allowedSenders"),
                regexes = optionalStringList(
                    parent = it,
                    name = "regexes",
                    maximumItemLength = 4_096,
                    trimItems = false,
                    ignoreCaseForDuplicates = false,
                ),
                forwardTemplate = optionalString(it, "forwardTemplate", MAXIMUM_TEMPLATE_LENGTH),
            ).also { parsed ->
                if (
                    parsed.allowedSenders == null &&
                    parsed.regexes == null &&
                    parsed.forwardTemplate == null
                ) {
                    throw ProvisioningException(
                        "Configuration value 'filters' does not contain a supported setting.",
                    )
                }
            }
        }
        if (
            masterEnabled == null &&
            whatsApp == null &&
            telegram == null &&
            sms == null &&
            filters == null
        ) {
            throw ProvisioningException("The configuration does not contain a supported setting.")
        }
        return ProvisionedConfiguration(
            masterEnabled = masterEnabled,
            whatsApp = whatsApp,
            telegram = telegram,
            sms = sms,
            filters = filters,
        )
    }

    private fun requireOnlyKeys(parent: JSONObject, location: String, allowed: Set<String>) {
        val keys = parent.keys()
        while (keys.hasNext()) {
            val key = keys.next()
            if (key !in allowed) {
                throw ProvisioningException(
                    "Configuration $location contains an unsupported value.",
                )
            }
        }
    }

    private fun parseJson(json: String, errorMessage: String): JSONObject {
        return try {
            JSONObject(json)
        } catch (error: JSONException) {
            throw ProvisioningException(errorMessage, error)
        }
    }

    private fun requiredObject(parent: JSONObject, name: String): JSONObject {
        return parent.opt(name) as? JSONObject
            ?: throw ProvisioningException("Configuration value '$name' must be an object.")
    }

    private fun optionalObject(parent: JSONObject, name: String): JSONObject? {
        if (!parent.has(name)) {
            return null
        }
        return parent.opt(name) as? JSONObject
            ?: throw ProvisioningException("Configuration value '$name' must be an object.")
    }

    private fun requiredString(parent: JSONObject, name: String, maximumLength: Int): String {
        val value = parent.opt(name) as? String
            ?: throw ProvisioningException("Configuration value '$name' must be text.")
        val trimmed = value.trim()
        if (trimmed.isEmpty() || trimmed.length > maximumLength) {
            throw ProvisioningException(
                "Configuration value '$name' must contain 1 to $maximumLength characters.",
            )
        }
        return trimmed
    }

    private fun requiredBoolean(parent: JSONObject, name: String): Boolean {
        return parent.opt(name) as? Boolean
            ?: throw ProvisioningException("Configuration value '$name' must be true or false.")
    }

    private fun optionalBoolean(parent: JSONObject, name: String): Boolean? {
        if (!parent.has(name)) {
            return null
        }
        return requiredBoolean(parent, name)
    }

    private fun optionalString(parent: JSONObject, name: String, maximumLength: Int): String? {
        if (!parent.has(name)) {
            return null
        }
        val value = parent.opt(name) as? String
            ?: throw ProvisioningException("Configuration value '$name' must be text.")
        if (value.length > maximumLength) {
            throw ProvisioningException(
                "Configuration value '$name' cannot exceed $maximumLength characters.",
            )
        }
        return value
    }

    private fun optionalSenderRuleList(parent: JSONObject, name: String): List<SenderRule>? {
        if (!parent.has(name)) {
            return null
        }
        val values = parent.opt(name) as? JSONArray
            ?: throw ProvisioningException("Configuration value '$name' must be an array.")
        if (values.length() > MAXIMUM_LIST_ENTRIES) {
            throw ProvisioningException(
                "Configuration value '$name' cannot contain more than $MAXIMUM_LIST_ENTRIES entries.",
            )
        }
        val result = mutableListOf<SenderRule>()
        repeat(values.length()) { index ->
            val item = values.opt(index) as? JSONObject
                ?: throw ProvisioningException(
                    "Configuration value '$name' must contain only sender-rule objects.",
                )
            requireOnlyKeys(item, "sender rule", setOf("value", "regex"))
            val isRegex = requiredBoolean(item, "regex")
            val rawValue = item.opt("value") as? String
                ?: throw ProvisioningException("Configuration value 'value' must be text.")
            val rule = SenderRule(
                value = if (isRegex) rawValue else rawValue.trim(),
                isRegex = isRegex,
            )
            if (
                rule.value.isBlank() ||
                rule.value.length > 256 ||
                rule.value.contains('\r') ||
                rule.value.contains('\n')
            ) {
                throw ProvisioningException(
                    "Configuration value '$name' contains an invalid entry at position ${index + 1}.",
                )
            }
            if (result.none { it.isRegex == rule.isRegex && it.value == rule.value }) {
                result.add(rule)
            }
        }
        return result
    }

    private fun optionalStringList(
        parent: JSONObject,
        name: String,
        maximumItemLength: Int,
        trimItems: Boolean,
        ignoreCaseForDuplicates: Boolean,
    ): List<String>? {
        if (!parent.has(name)) {
            return null
        }
        val values = parent.opt(name) as? JSONArray
            ?: throw ProvisioningException("Configuration value '$name' must be an array.")
        if (values.length() > MAXIMUM_LIST_ENTRIES) {
            throw ProvisioningException(
                "Configuration value '$name' cannot contain more than $MAXIMUM_LIST_ENTRIES entries.",
            )
        }
        val result = mutableListOf<String>()
        repeat(values.length()) { index ->
            val raw = values.opt(index) as? String
                ?: throw ProvisioningException("Configuration value '$name' must contain only text entries.")
            val value = if (trimItems) raw.trim() else raw
            if (
                value.isBlank() ||
                value.length > maximumItemLength ||
                value.contains('\r') ||
                value.contains('\n')
            ) {
                throw ProvisioningException(
                    "Configuration value '$name' contains an invalid entry at position ${index + 1}.",
                )
            }
            if (result.none { it.equals(value, ignoreCase = ignoreCaseForDuplicates) }) {
                result.add(value)
            }
        }
        return result
    }

    private fun requiredInteger(parent: JSONObject, name: String): Int {
        val value = parent.opt(name) as? Number
            ?: throw ProvisioningException("Configuration value '$name' must be an integer.")
        val longValue = value.toLong()
        if (value.toDouble() != longValue.toDouble() || longValue !in Int.MIN_VALUE..Int.MAX_VALUE) {
            throw ProvisioningException("Configuration value '$name' must be an integer.")
        }
        return longValue.toInt()
    }

    private fun requiredBase64(parent: JSONObject, name: String, requiredSize: Int? = null): ByteArray {
        val encoded = requiredString(parent, name, MAX_BUNDLE_BYTES)
        val decoded = try {
            Base64.getDecoder().decode(encoded)
        } catch (error: IllegalArgumentException) {
            throw ProvisioningException("Configuration value '$name' is not valid Base64.", error)
        }
        if (requiredSize != null && decoded.size != requiredSize) {
            throw ProvisioningException("Configuration value '$name' has an invalid length.")
        }
        return decoded
    }

    private data class PreferenceSnapshot(private val values: Map<String, Any?>) {
        @SuppressLint("UseKtx")
        fun restore(prefs: android.content.SharedPreferences) {
            val editor = prefs.edit()
            values.forEach { (key, value) ->
                when (value) {
                    null -> editor.remove(key)
                    is Boolean -> editor.putBoolean(key, value)
                    is String -> editor.putString(key, value)
                    else -> error("Unsupported preference value")
                }
            }
            check(editor.commit()) { "Could not restore channel configuration" }
        }

        companion object {
            fun capture(
                prefs: android.content.SharedPreferences,
                keys: Set<String>,
            ): PreferenceSnapshot {
                val storedValues = prefs.all
                return PreferenceSnapshot(
                    keys.associateWith { key ->
                        if (prefs.contains(key)) storedValues[key] else null
                    },
                )
            }
        }
    }
}
